# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 441)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(521, 441))
        Form.setMaximumSize(QtCore.QSize(521, 441))
        self.btn_open_add = QtWidgets.QPushButton(Form)
        self.btn_open_add.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.btn_open_add.setShortcut("")
        self.btn_open_add.setObjectName("btn_open_add")
        self.btn_delete = QtWidgets.QPushButton(Form)
        self.btn_delete.setGeometry(QtCore.QRect(10, 120, 111, 31))
        self.btn_delete.setObjectName("btn_delete")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(130, 400, 181, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_delete_version = QtWidgets.QPushButton(Form)
        self.pushButton_delete_version.setGeometry(QtCore.QRect(330, 400, 181, 31))
        self.pushButton_delete_version.setObjectName("pushButton_delete_version")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(130, 30, 381, 361))
        self.listWidget.setObjectName("listWidget")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 111, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_open_add.setText(_translate("Form", "Добавить"))
        self.btn_delete.setText(_translate("Form", "Удалить"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        self.pushButton_delete_version.setText(_translate("Form", "Удалить"))
        self.label.setText(_translate("Form", "Выбор версии:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
